server:
  servlet:
    context-path: /resource-server-jwt
  port: 8888

spring:
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth